import { StyleDefinition } from '@/types'

export const styleDefinitions: Record<string, StyleDefinition> = {
  vanilla: {
    id: 'vanilla',
    name: 'Vanilla Girl',
    emoji: '🤍',
    description: '베이지, 아이보리 계열의 성숙하고 우아한 스타일',
    characteristics: [
      '올드머니 감성',
      '성숙하고 우아한 분위기',
      '자연스러운 고급스러움',
      '심플하면서도 세련된',
    ],
    colorPatterns: ['beige', 'ivory', 'cream', 'tan', 'camel', 'sand', 'nude'],
    makeupStyle: ['natural', 'neutral', 'subtle', 'nude'],
    clothingStyle: ['classic', 'elegant', 'sophisticated', 'tailored'],
    imagePrompt: `Transform this person into a classic Disney princess illustration style, similar to Cinderella or Beauty and the Beast aesthetic. Keep the background as is. Square 1:1 aspect ratio. Soft, elegant art style with romantic colors.`,
    gradientColors: 'from-amber-100 via-orange-50 to-yellow-50',
  },
  strawberry: {
    id: 'strawberry',
    name: 'Strawberry Girl',
    emoji: '🍓',
    description: '핑크, 레드 계열의 러블리하고 화려한 스타일',
    characteristics: [
      '러블리하고 귀여운 감성',
      '화려한 색감',
      '소녀 바이브',
      '아이돌 같은 분위기',
    ],
    colorPatterns: ['pink', 'red', 'purple', 'magenta', 'rose', 'fuchsia', 'hot pink'],
    makeupStyle: ['colorful', 'vibrant', 'bright', 'bold', 'glittery'],
    clothingStyle: ['cute', 'girly', 'dress', 'skirt', 'lovely', 'sweet'],
    imagePrompt: `Transform this person into Sailor Moon anime art style with city pop aesthetic. Keep the background as is. Square 1:1 aspect ratio. Vibrant colors, sparkling effects, magical girl aesthetic.`,
    gradientColors: 'from-pink-100 via-rose-50 to-purple-50',
  },
  coffee: {
    id: 'coffee',
    name: 'Coffee Girl',
    emoji: '☕',
    description: '블랙, 무채색 계열의 시크하고 트렌디한 스타일',
    characteristics: [
      '쿨하고 시크한 분위기',
      '중성적인 매력',
      '트렌디하고 모던한',
      '도시적인 감성',
    ],
    colorPatterns: ['black', 'gray', 'brown', 'charcoal', 'slate', 'espresso', 'mocha'],
    makeupStyle: ['edgy', 'sharp', 'contoured', 'smokey', 'bold'],
    clothingStyle: ['modern', 'chic', 'minimal', 'edgy', 'urban', 'trendy'],
    imagePrompt: `Transform this person into Bratz character illustration style. Keep the background as is. Square 1:1 aspect ratio. Bold fashion, dramatic features, trendy and edgy aesthetic.`,
    gradientColors: 'from-stone-100 via-neutral-100 to-gray-100',
  },
  clean: {
    id: 'clean',
    name: 'Clean Girl',
    emoji: '🤍',
    description: '화이트, 뉴트럴 계열의 자연스럽고 깔끔한 스타일',
    characteristics: [
      '자연스럽고 편안한',
      '깔끔하고 미니멀한',
      '편한 캐주얼 스타일',
      '건강한 아름다움',
    ],
    colorPatterns: ['white', 'off-white', 'light gray', 'pale', 'neutral', 'natural'],
    makeupStyle: ['natural', 'fresh', 'minimal', 'dewy', 'clean'],
    clothingStyle: ['casual', 'comfortable', 'simple', 'relaxed', 'everyday'],
    imagePrompt: `Transform this person into Studio Ghibli illustration style, similar to My Neighbor Totoro or The Wind Rises. Keep the background as is. Square 1:1 aspect ratio. Soft watercolor aesthetic, natural and peaceful atmosphere.`,
    gradientColors: 'from-slate-50 via-gray-50 to-zinc-50',
  },
}
